name: 04_CICD_Example

on: [push]
env:
  APPLICATION_NAME: app2
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python environment
      uses: actions/setup-python@v1.1.1
    - name: Install requirements
      run: pip install --quiet --requirement ./04_CICD_Example/04_requirements.txt
    - name: Lint code
      run: |
        flake8 --ignore=E501,E231 ./04_CICD_Example/*.py
        pylint --disable=C0301 --disable=C0326 ./04_CICD_Example/*.py
    - name: Run unit tests
      run: |
        python -m unittest --verbose --failfast
