name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python env
        uses: actions/@setup-python@4.7.1
      - name: Run Python script
        uses: jannekem/run-python-script-action@v1.6
        with:
          script: "./challenge_script.py"
